### ISSUE TITLE
Using Metrics and Standard logging

### ISSUE THREAD

**Issue by imraazrally** [SumoLogic/js-logging-sdk#30]
Hi, 

I'm trying to use this sdk for standard logging. `sumoLogger.log()` 
However, I also want to use it for metrics. `sumoLogger.log({path, value})`

enabling the `graphite: true` throws an **error** when trying to use it for standard logging. It looks like the path and value fields are mandatory as soon as you enable graphite.

```Sumo Logic requires both \'path\' and \'value\' properties to be provided in the message object```

Is there a way around this? 

Have multiple loggers (as shown below) does not seem to solve the issue either. 
```
 const logger1 = new SumoLogger(opts1)
 const logger2 = new SumoLogger(opts2)
```

**Comment by clementallen** [comment]
@imraazrally currently enabled graphite requires all log requests to be in graphite form.

The best solution would probably be to allow enabling graphite to be possible when both creating an instance or when calling the log method as part of the optional config passed in.
If you wish to create a PR for this feature that would be wonderful otherwise I may find some time in the next week or so to look at it.

I think multiple loggers doesn't work currently as the config values are currently shared between all instances which should really be fixed.  It should work when the config is moved into the constructor which is on my todo list!
